CREATE TABLE revenue(
	PRIMARY_KEY VARCHAR(25) PRIMARY KEY,
	STATE VARCHAR(25),
	YEAR INT,
	ENROLL INT,
	TOTAL_REVENUE NUMERIC,
	FEDERAL_REVENUE NUMERIC,
	STATE_REVENUe NUMERIC,
	LOCAL_REVENUE NUMERIC,
	TOTAL_EXPENDITURE NUMERIC,
	INSTRUCTION_EXPENDITURE	NUMERIC,
	SUPPORT_SERVICES_EXPENDITURE NUMERIC,
	OTHER_EXPENDITURE NUMERIC,
	CAPITAL_OUTLAY_EXPENDITURE NUMERIC
	)
CREATE TABLE math_test_scores(
	Year INT,
	Jurisdiction VARCHAR(25),
	All_Students VARCHAR(25),
	Average_Scale_Score INT,
	Key VARCHAR(25) 
	
)
	